### ISSUE TITLE
Bot down?

### ISSUE THREAD

**Issue by cfuendev** [Bernardozomer/ivone-bot#1]
I tried running a few commands, but not even `/ping` works. Is it down for maintenance/updates?

![image](https://user-images.githubusercontent.com/65634520/129807228-fdf1ca49-d58f-463f-bfad-f4fe6123d2bf.png)

Bot appears disconnected as well.

![image](https://user-images.githubusercontent.com/65634520/129807416-059f7bd6-359b-4bdc-bb8f-7aa7b4d2d258.png)

**Comment by Bernardozomer** [comment]
Yes, it's down. Sorry for not announcing it beforehand, but that's actually why it's offline; some functions aren't working because I didn't prepare them to deal with `None` values, such as the ones that iterate over every server the bot is in. Namely, the ones responsible for sending announcements and _saving data from memory to disk_.

Currently, I'm trying to find a way to stop the process without losing any data so that I can apply the fix and restart it. It's only suspended at the moment, though.

I should be able to get it up and running with the bug fixed in little time if I sacrificed the data, but I don't know how many of the 17 servers it's in (minus 5 personal ones) are actually using it. Quite the conundrum.
